Conditionally show output logs on fail

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -55,7 +55,16 @@ jobs:
       - checkout
       - attach_workspace:
           at: .
-      - run: npm run test:publish || cat test/publish/test.log
+      - run:
+          name: Test and output logs
+          command: |
+            npm run test:publish
+            EXIT_CODE=$?
+            if [ $EXIT_CODE -gt 0 ] then
+              cat test/publish/test.log # show logs here if test failed
+            fi
+            exit $EXIT_CODE
+      - run: cat test/publish/test.log
 
   test-kovan:
     <<: *env_defaults
