Update circle ci build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -74,279 +74,357 @@ commands:
                     :
                 shell: /bin/sh
 jobs:
-  prepare:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - restore_cache:
-          keys:
-            - 'v2-dependencies-{{ checksum "package-lock.json" }}'
-      - run: npm install
-      - save_cache:
-          key: 'v2-dependencies-{{ checksum "package-lock.json" }}'
-          paths:
-            - node_modules
-      - persist_to_workspace:
-          root: .
-          paths:
-            - node_modules
-
-  fork-prepare-deploy:
-    <<: *env_defaults
-    parameters:
-      network:
-        type: string
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - fork_prepare_deploy:
-          network: << parameters.network >>
-
-  fork-deploy:
-    <<: *env_defaults
-    parameters:
-      network:
-        type: string
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - fork_deploy:
-          network: << parameters.network >>
-
-  fork-test-prod:
-    <<: *env_defaults
-    parameters:
-      network:
-        type: string
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - fork_test_prod:
-          network: << parameters.network >>
-
-  lint:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: npm run lint
-
-  test-contracts:
-    <<: *env_defaults
-    resource_class: large
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: npx buidler compile --showsize --optimizer
-      - run:
-          name: Test and output gas used
-          command: |
-            set +e
-            npm test
-            EXIT_CODE=$?
-            cat test-gas-used.log
-            printf "\\n"
-            exit $EXIT_CODE
-
-  test-contracts-legacy:
-    <<: *env_defaults
-    resource_class: large
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: npm run compile:legacy
-      - run: npx buidler test:legacy
-
-  test-ovm:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Compile in OVM, enforcing size limit
-          command: |
-            npx buidler compile --ovm --optimizer --showsize
-
-  test-publish:
-    <<: *env_defaults
-    resource_class: large
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Test and output logs
-          command: |
-            set +e
-            npm run test:publish
-            EXIT_CODE=$?
-            if [ $EXIT_CODE -gt 0 ]; then
-              tail -n 2000 test/publish/test.log; # show tail of logs here if test failed
-            fi
-            npx ansi-to-html --newline --bg black test/publish/test.log > test/publish/test-log.html
-            exit $EXIT_CODE
-      - store_artifacts:
-          path: test/publish/test-log.html
-          destination: test-log.html
-
-  test-deployments:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: npm run test:deployments
-
-  test-local:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: npm run test:local
-
-  coverage-report:
-    <<: *env_defaults
-    resource_class: xlarge
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: NODE_OPTIONS=--max_old_space_size=4096 npm run coverage
-      - run: bash <(curl -s https://codecov.io/bash)
-
-  pack:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: npm run pack
-      - store_artifacts:
-          path: browser.js
-
-  gas-report:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run: npm run test:gas && npx codechecks
-
-  test-kovan:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - testnet_pvt:
-          network: kovan
-      - etherscan_check:
-          network: kovan
-
-  test-rinkeby:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - testnet_pvt:
-          network: rinkeby
-      - etherscan_check:
-          network: rinkeby
-
-  # Ropsten paused (see above).
-  # test-ropsten:
-  #   <<: *env_defaults
-  #   steps:
-  #     - checkout
-  #     - attach_workspace:
-  #         at: .
-  #     - testnet_pvt:
-  #         network: ropsten
-  #     - etherscan_check:
-  #         network: ropsten
-
-  test-mainnet:
-    <<: *env_defaults
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      # - run: No PVT for mainnet just yet
-      - etherscan_check:
-          network: mainnet
-
-  slither:
-    docker:
-      - image: trailofbits/eth-security-toolbox
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Show Slither output
-          # ignore slither error codes
-          command: |
-            set +e
-            slither .
-            exit 0
-
+    coverage-report:
+        docker:
+            - image: circleci/node:12.18
+        resource_class: xlarge
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: NODE_OPTIONS=--max_old_space_size=4096 npm run coverage
+            - run: bash <(curl -s https://codecov.io/bash)
+        working_directory: ~/repo
+    fork-deploy:
+        docker:
+            - image: circleci/node:12.18
+        parameters:
+            network:
+                type: string
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - fork_deploy:
+                network: << parameters.network >>
+        working_directory: ~/repo
+    fork-prepare-deploy:
+        docker:
+            - image: circleci/node:12.18
+        parameters:
+            network:
+                type: string
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - fork_prepare_deploy:
+                network: << parameters.network >>
+        working_directory: ~/repo
+    fork-test-prod:
+        docker:
+            - image: circleci/node:12.18
+        parameters:
+            network:
+                type: string
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - fork_test_prod:
+                network: << parameters.network >>
+        working_directory: ~/repo
+    gas-report:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: npm run test:gas && npx codechecks
+        working_directory: ~/repo
+    lint:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: npm run lint
+        working_directory: ~/repo
+    pack:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: npm run pack
+            - store_artifacts:
+                path: browser.js
+        working_directory: ~/repo
+    prepare:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - restore_cache:
+                keys:
+                    - v2-dependencies-{{ checksum "package-lock.json" }}
+            - run: npm install
+            - save_cache:
+                key: v2-dependencies-{{ checksum "package-lock.json" }}
+                paths:
+                    - node_modules
+            - persist_to_workspace:
+                paths:
+                    - node_modules
+                root: .
+        working_directory: ~/repo
+    slither:
+        docker:
+            - image: trailofbits/eth-security-toolbox
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run:
+                command: |
+                    set +e
+                    slither .
+                    exit 0
+                name: Show Slither output
+    test-contracts:
+        docker:
+            - image: circleci/node:12.18
+        resource_class: large
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: npx buidler compile --showsize --optimizer
+            - run:
+                command: |
+                    set +e
+                    npm test
+                    EXIT_CODE=$?
+                    cat test-gas-used.log
+                    printf "\\n"
+                    exit $EXIT_CODE
+                name: Test and output gas used
+        working_directory: ~/repo
+    test-contracts-legacy:
+        docker:
+            - image: circleci/node:12.18
+        resource_class: large
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: npm run compile:legacy
+            - run: npx buidler test:legacy
+        working_directory: ~/repo
+    test-deployments:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: npm run test:deployments
+        working_directory: ~/repo
+    test-kovan:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - testnet_pvt:
+                network: kovan
+            - etherscan_check:
+                network: kovan
+        working_directory: ~/repo
+    test-local:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run: npm run test:local
+        working_directory: ~/repo
+    test-mainnet:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - etherscan_check:
+                network: mainnet
+        working_directory: ~/repo
+    test-ovm:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run:
+                command: |
+                    npx buidler compile --ovm --optimizer
+                name: Compile in OVM, enforcing size limit
+        working_directory: ~/repo
+    test-publish:
+        docker:
+            - image: circleci/node:12.18
+        resource_class: large
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - run:
+                command: |
+                    set +e
+                    npm run test:publish
+                    EXIT_CODE=$?
+                    if [ $EXIT_CODE -gt 0 ]; then
+                      tail -n 2000 test/publish/test.log; # show tail of logs here if test failed
+                    fi
+                    npx ansi-to-html --newline --bg black test/publish/test.log > test/publish/test-log.html
+                    exit $EXIT_CODE
+                name: Test and output logs
+            - store_artifacts:
+                destination: test-log.html
+                path: test/publish/test-log.html
+        working_directory: ~/repo
+    test-rinkeby:
+        docker:
+            - image: circleci/node:12.18
+        steps:
+            - checkout
+            - attach_workspace:
+                at: .
+            - testnet_pvt:
+                network: rinkeby
+            - etherscan_check:
+                network: rinkeby
+        working_directory: ~/repo
+version: 2.1
 workflows:
     dev:
         jobs:
             - prepare
-      - test-ovm:
-          requires:
-            - prepare
-      - test-publish:
-          requires:
-            - prepare
-      - test-deployments:
-          requires:
-            - prepare
-      - test-local:
-          requires:
-            - prepare
-      - pack:
-          requires:
-            - prepare
-      # - coverage-report:
-      #     requires:
-      #       - prepare
-      - gas-report:
-          requires:
-            - prepare
-      - slither:
-          requires:
-            - prepare
-      # ~~~~~~~~~~~~~~~ KOVAN ~~~~~~~~~~~~~~~ #
-      - test-kovan:
-          requires:
-            - prepare
-          filters:
-            branches:
-              only: staging
-      # ~~~~~~~~~~~~~~~ RINKEBY ~~~~~~~~~~~~~~~ #
-      - test-rinkeby:
-          requires:
-            - prepare
-          filters:
-            branches:
-              only: staging
-      # ~~~~~~~~~~~~~~~ MAINNET ~~~~~~~~~~~~~~~ #
-      - test-mainnet:
-          requires:
-            - prepare
-          filters:
-            branches:
-              only: master
-      # ~~~~~~~~~~~~~~~ ROPSTEN ~~~~~~~~~~~~~~~ #
-      # Ropsten paused (see above).
+            - lint:
+                requires:
+                    - prepare
+            - test-contracts:
+                requires:
+                    - prepare
+            - test-contracts-legacy:
+                requires:
+                    - prepare
+            - test-ovm:
+                requires:
+                    - prepare
+            - test-publish:
+                requires:
+                    - prepare
+            - test-deployments:
+                requires:
+                    - prepare
+            - test-local:
+                requires:
+                    - prepare
+            - pack:
+                requires:
+                    - prepare
+            - coverage-report:
+                requires:
+                    - prepare
+            - gas-report:
+                requires:
+                    - prepare
+            - slither:
+                requires:
+                    - prepare
+            - test-kovan:
+                filters:
+                    branches:
+                        only: staging
+                requires:
+                    - prepare
+            - test-rinkeby:
+                filters:
+                    branches:
+                        only: staging
+                requires:
+                    - prepare
+            - test-mainnet:
+                filters:
+                    branches:
+                        only: master
+                requires:
+                    - prepare
+    forkprod-tests:
+        jobs:
+            - prepare:
+                filters:
+                    branches:
+                        only: develop
+            - fork-prepare-deploy:
+                name: fork-prepare-deploy-mainnet
+                network: mainnet
+                requires:
+                    - prepare
+            - fork-deploy:
+                name: fork-deploy-mainnet
+                network: mainnet
+                requires:
+                    - fork-prepare-deploy-mainnet
+            - fork-test-prod:
+                name: fork-test-prod-mainnet
+                network: mainnet
+                requires:
+                    - fork-deploy-mainnet
+            - fork-prepare-deploy:
+                filters:
+                    branches:
+                        only: develop
+                name: fork-prepare-deploy-rinkeby
+                network: rinkeby
+                requires:
+                    - prepare
+            - fork-deploy:
+                filters:
+                    branches:
+                        only: develop
+                name: fork-deploy-rinkeby
+                network: rinkeby
+                requires:
+                    - fork-prepare-deploy-rinkeby
+            - fork-test-prod:
+                filters:
+                    branches:
+                        only: develop
+                name: fork-test-prod-rinkeby
+                network: rinkeby
+                requires:
+                    - fork-deploy-rinkeby
+            - fork-prepare-deploy:
+                filters:
+                    branches:
+                        only: develop
+                name: fork-prepare-deploy-kovan
+                network: rinkeby
+                requires:
+                    - prepare
+            - fork-deploy:
+                filters:
+                    branches:
+                        only: develop
+                name: fork-deploy-kovan
+                network: rinkeby
+                requires:
+                    - fork-prepare-deploy-kovan
+            - fork-test-prod:
+                filters:
+                    branches:
+                        only: develop
+                name: fork-test-prod-kovan
+                network: rinkeby
+                requires:
+                    - fork-deploy-kovan
+    version: 2
+
