Silencing CI to focus on deploy script job problem

diff --git a/.circleci/src/jobs/job-test-deploy-script.yml b/.circleci/src/jobs/job-test-deploy-script.yml
--- a/.circleci/src/jobs/job-test-deploy-script.yml
+++ b/.circleci/src/jobs/job-test-deploy-script.yml
@@ -8,14 +8,14 @@ steps:
   - run:
       name: Test and output logs
       command: |
-        set +e
+        # set +e
         npm run test:publish
-        EXIT_CODE=$?
-        if [ $EXIT_CODE -gt 0 ]; then
-          tail -n 2000 test/publish/test.log; # show tail of logs here if test failed
-        fi
-        npx ansi-to-html --newline --bg black test/publish/test.log > test/publish/test-log.html
-        exit $EXIT_CODE
+        # EXIT_CODE=$?
+        # if [ $EXIT_CODE -gt 0 ]; then
+        #   tail -n 2000 test/publish/test.log; # show tail of logs here if test failed
+        # fi
+        # npx ansi-to-html --newline --bg black test/publish/test.log > test/publish/test-log.html
+        # exit $EXIT_CODE
   - store_artifacts:
       path: test/publish/test-log.html
       destination: test-log.html
